find_path(GLFW3_INCLUDE_DIR NAMES GLFW/glfw3.h)

set(GLFW3_NAMES ${GLFW3_NAMES} glfw3 glfw)
find_library(GLFW3_LIBRARY NAMES ${GLFW3_NAMES})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLFW3 DEFAULT_MSG GLFW3_INCLUDE_DIR GLFW3_LIBRARY)