set(CMAKE_SYSTEM_NAME Linux)

if(NOT ${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "(i386)|(i686)")
    set(CMAKE_SYSTEM_PROCESSOR i386)
    if(${CMAKE_HOST_SYSTEM_PROCESSOR} MATCHES "(amd64)|(x86_64)")
        set(CMAKE_C_COMPILER gcc)
        set(CMAKE_CXX_COMPILER g++)
        set(CMAKE_ASM_COMPILER gcc)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m32")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m32")
    else()
        set(CMAKE_C_COMPILER i686-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER i686-linux-gnu-g++)
        set(CMAKE_ASM_COMPILER i686-linux-gnu-gcc)
    endif()
endif()

set(CMAKE_FIND_ROOT_PATH /usr)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
